apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoinsolar-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bitcoinsolar-backend
  template:
    metadata:
      labels:
        app: bitcoinsolar-backend
    spec:
      containers:
        - name: backend
          image: ${REGISTRY_IMAGE}:latest
          ports:
            - containerPort: 8080
