apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitcoinsolar-backend
spec:
  rules:
    - host: api.bitcoinsolar.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bitcoinsolar-backend
                port:
                  number: 80
