user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    sendfile on;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream blsr_backend {
        server blsr-backend:8080;
    }

    server {
        listen 80;
        server_name api.bitcoinsolar.org;

        location / {
            proxy_pass http://blsr_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 443 ssl;
        server_name api.bitcoinsolar.org;

        ssl_certificate /etc/letsencrypt/live/api.bitcoinsolar.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.bitcoinsolar.org/privkey.pem;

        location / {
            proxy_pass http://blsr_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
