server {
    listen 80;
    server_name operator.bitcoinsolar.org;

    root /var/www/operator.bitcoinsolar.org;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
