version: "3.9"

services:
  bitcoinsolar-web:
    build:
      context: ./website
    container_name: bitcoinsolar-web
    environment:
      - BLSR_API_VERSION=1.0
      - BLSR_NODE_NAME=LYNNIC_ACTIVE
      - BLSR_NETWORK=polygon-mainnet
      - PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped
